language: node_js

env:
  - DATABASE_URL=postgresql://@localhost:5432/waiter_app_db

node_js:  
  - 14.15.0

before_script:
  - psql -c 'create database  waiter_app_db;' -U postgres
  - psql -U postgres -d waiter_app_db -a -f tables.sql

services:
  - postgresql